# Generated by Django 4.2.16 on 2024-11-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=255)),
                ('bank_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_code', models.CharField(max_length=255)),
                ('prdt_name', models.CharField(max_length=255)),
                ('prdt_code', models.CharField(max_length=255)),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('join_deny', models.CharField(max_length=255)),
                ('join_member', models.TextField()),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.bank')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(max_length=255)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField()),
                ('max_intr_rate', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.bank')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.productcategory'),
        ),
    ]
