# Generated by Django 4.2.16 on 2024-11-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
    ]
